// Define all possible module names as a const array
const MODULE_NAMES = [
  'warehouse-mgmt',
  'warehouse-admin',
  'warehouse-profile',
  'warehouse-locations',
  'warehouse-labor',
  'warehouse-dock',
  'warehouse-yard',
  'warehouse-reports',
  'warehouse-settings',
  'warehouse-user-tasks',
  'warehouse-user-inbound',
  'warehouse-user-outbound',
  'warehouse-user-inventory',
  'warehouse-user-reports',
  'warehouse-user-profile',
  'warehouse-user-inbound-appointments',
  'warehouse-user-inbound-asn',
  'warehouse-user-inbound-grn',
  'warehouse-user-inbound-quality',
  'warehouse-user-inbound-putaway',
  'warehouse-user-inbound-cross-dock',
  'warehouse-user-inventory-inquiry',
  'warehouse-user-inventory-moves',
  'warehouse-user-inventory-adjustments',
  'warehouse-user-inventory-replenishment',
  'warehouse-user-inventory-cycle-count',
  'warehouse-user-outbound-order-workbench',
  'warehouse-user-outbound-waves',
  'warehouse-user-outbound-picking',
  'warehouse-user-outbound-packing',
  'warehouse-user-outbound-shipping',
  'warehouse-user-outbound-load-planning',
  'warehouse-user-returns-customer-returns',
  'warehouse-user-returns-kitting',
  'warehouse-user-exceptions',
  'warehouse-user-reports-my-kpis',
  'warehouse-user-mobile-task-list',
  'warehouse-user-mobile-scan-station',
  'warehouse-user-mobile-messages',
  'warehouse-user-mobile',
  'warehouse-profile',
  'warehouse-putaway-rules',
  'warehouse-replenishment-rules',
  'warehouse-cycle-count-rules',
  'warehouse-task-assignment',
  'warehouse-monitoring',
  'warehouse-inventory-config',
  'warehouse-user-task-management',
] as const;

export type ModuleName = typeof MODULE_NAMES[number];

export function isValidModuleName(name: string): name is ModuleName {
  return (MODULE_NAMES as readonly string[]).includes(name);
}
